import type { Trip } from "~/types/search/results";

export const defaultTrips: Trip[] = [
  {
    id: "gb-01",
    operatorId: "gobus",
    operatorName: "Go Bus",
    operatorAbbr: "GB",
    operatorLogoBg: "bg-red-950/20 text-red-500 dark:bg-red-900/30",
    busClass: "Elite Plus (MCV 600)",
    busModel: "Mercedes MCV 600 Coach",
    rating: 4.8,
    reviewsCount: 820,
    departureTime: "08:30 AM",
    departureStation: "Almaza Terminal (Heliopolis)",
    departureCity: "Cairo",
    arrivalTime: "11:15 AM",
    arrivalStation: "Sidi Gaber Terminal",
    arrivalCity: "Alexandria",
    duration: "2h 45m",
    routeType: "Non-stop Express",
    routeHighlight: "Direct Route",
    highwayBadge: "Cairo - Alex Desert Road",
    price: 145,
    availableSeats: 4,
    isDirect: true,
    isVerified: true,
    timeSlot: "morning",
    classType: "vip",
    amenities: [
      { id: "wifi", name: "Wi-Fi", icon: "ph:wifi-high-bold" },
      { id: "usb", name: "Power / USB", icon: "ph:plug-bold" },
      { id: "wc", name: "WC", icon: "ph:toilet-bold", iconClass: "text-emerald-500" },
      { id: "drinks", name: "Hot Drinks", icon: "ph:coffee-bold" },
      { id: "seats", name: "Leather Recliner", icon: "ph:armchair-bold" },
    ],
  },
  {
    id: "bb-01",
    operatorId: "bluebus",
    operatorName: "BlueBus",
    operatorAbbr: "BB",
    operatorLogoBg: "bg-blue-950/20 text-blue-500 dark:bg-blue-900/30",
    busClass: "First Class VIP (2+1)",
    busModel: "Travego 16 SHD • 2+1 Seating",
    rating: 4.9,
    reviewsCount: 410,
    departureTime: "09:15 AM",
    departureStation: "Ramses Central Station",
    departureCity: "Cairo",
    arrivalTime: "11:45 AM",
    arrivalStation: "Moharam Bek Central",
    arrivalCity: "Alexandria",
    duration: "2h 30m",
    routeType: "Non-stop Express",
    routeHighlight: "Fastest Route",
    highwayBadge: "Fastest Express Journey",
    price: 220,
    availableSeats: 9,
    isDirect: true,
    isVerified: true,
    timeSlot: "morning",
    classType: "vip",
    amenities: [
      { id: "screen", name: "Personal Screen", icon: "ph:television-bold" },
      { id: "seats", name: "2+1 Extra Legroom", icon: "ph:armchair-bold" },
      { id: "wifi", name: "5G Wi-Fi", icon: "ph:wifi-high-bold" },
      { id: "drinks", name: "Cold Beverage & Snack", icon: "ph:brandy-bold" },
    ],
  },
  {
    id: "sj-01",
    operatorId: "superjet",
    operatorName: "Super Jet (الاتحاد العربي)",
    operatorAbbr: "SJ",
    operatorLogoBg: "bg-emerald-950/20 text-emerald-500 dark:bg-emerald-900/30",
    busClass: "Super Star AC",
    busModel: "National Bus Fleet • 30kg Luggage",
    rating: 4.7,
    reviewsCount: 620,
    departureTime: "10:00 AM",
    departureStation: "Torgoman Gateway (Downtown)",
    departureCity: "Cairo",
    arrivalTime: "01:00 PM",
    arrivalStation: "Moharam Bek Station",
    arrivalCity: "Alexandria",
    duration: "3h 00m",
    routeType: "Agricultural Highway",
    routeHighlight: "Cheapest Fare",
    highwayBadge: "Direct to Moharam Bek",
    price: 110,
    availableSeats: 18,
    isDirect: true,
    isVerified: true,
    timeSlot: "morning",
    classType: "standard",
    amenities: [
      { id: "ac", name: "Climate Control AC", icon: "ph:snowflake-bold", iconClass: "text-cyan-500" },
      { id: "luggage", name: "30kg Checked Free Bags", icon: "ph:suitcase-bold" },
      { id: "usb", name: "Seat USB", icon: "ph:plug-bold" },
      { id: "light", name: "Reading Lights", icon: "ph:lamp-bold" },
    ],
  },
  {
    id: "gb-02",
    operatorId: "gobus",
    operatorName: "Go Bus",
    operatorAbbr: "GB",
    operatorLogoBg: "bg-amber-950/20 text-amber-500 dark:bg-amber-900/30",
    busClass: "Aero Luxury Bed (Flat Bed)",
    busModel: "Full Lie-Flat Recliners + Premium Lounge",
    rating: 4.9,
    reviewsCount: 390,
    departureTime: "11:30 AM",
    departureStation: "Almaza Lounge (Heliopolis)",
    departureCity: "Cairo",
    arrivalTime: "02:15 PM",
    arrivalStation: "Sidi Gaber Lounge",
    arrivalCity: "Alexandria",
    duration: "2h 45m",
    routeType: "Non-stop VIP",
    routeHighlight: "180° Lie-Flat Beds",
    highwayBadge: "Alex Desert Highway Non-Stop",
    price: 310,
    availableSeats: 2,
    isDirect: true,
    isVerified: true,
    timeSlot: "morning",
    classType: "sleeper",
    amenities: [
      { id: "bed", name: "Full Recline Bed", icon: "ph:bed-bold" },
      { id: "steward", name: "Hostess Service", icon: "ph:user-circle-bold" },
      { id: "meal", name: "Fresh Meal Box", icon: "ph:fork-knife-bold" },
      { id: "audio", name: "Noise-Cancelling Audio", icon: "ph:headphones-bold" },
      { id: "lounge", name: "VIP Lounge Access", icon: "ph:crown-bold", iconClass: "text-amber-500" },
    ],
  },
  {
    id: "bb-02",
    operatorId: "bluebus",
    operatorName: "BlueBus",
    operatorAbbr: "BB",
    operatorLogoBg: "bg-blue-950/20 text-blue-500 dark:bg-blue-900/30",
    busClass: "VIP Royal Comfort",
    busModel: "Mercedes Travego 2024",
    rating: 4.8,
    reviewsCount: 290,
    departureTime: "02:30 PM",
    departureStation: "Ramses Central Station",
    departureCity: "Cairo",
    arrivalTime: "05:00 PM",
    arrivalStation: "Moharam Bek Station",
    arrivalCity: "Alexandria",
    duration: "2h 30m",
    routeType: "Non-stop Express",
    routeHighlight: "Direct Highway",
    highwayBadge: "Cairo - Alex Desert Highway",
    price: 195,
    availableSeats: 12,
    isDirect: true,
    isVerified: true,
    timeSlot: "afternoon",
    classType: "vip",
    amenities: [
      { id: "wifi", name: "5G Wi-Fi", icon: "ph:wifi-high-bold" },
      { id: "usb", name: "USB Power", icon: "ph:plug-bold" },
      { id: "wc", name: "Deluxe Restroom", icon: "ph:toilet-bold" },
    ],
  },
  {
    id: "wd-01",
    operatorId: "westdelta",
    operatorName: "West & Mid Delta",
    operatorAbbr: "WD",
    operatorLogoBg: "bg-purple-950/20 text-purple-500 dark:bg-purple-900/30",
    busClass: "Classic AC Express",
    busModel: "Daewoo Royal Hi-Decker",
    rating: 4.5,
    reviewsCount: 450,
    departureTime: "06:45 PM",
    departureStation: "Torgoman Gateway (Downtown)",
    departureCity: "Cairo",
    arrivalTime: "09:45 PM",
    arrivalStation: "Moharam Bek Terminal",
    arrivalCity: "Alexandria",
    duration: "3h 00m",
    routeType: "Direct Corridor",
    routeHighlight: "Budget Express",
    highwayBadge: "Agricultural Highway",
    price: 100,
    availableSeats: 22,
    isDirect: true,
    isVerified: true,
    timeSlot: "evening",
    classType: "standard",
    amenities: [
      { id: "ac", name: "Air Conditioning", icon: "ph:snowflake-bold" },
      { id: "luggage", name: "Standard Luggage", icon: "ph:suitcase-bold" },
    ],
  },
];

export function useTrips() {
  const getTripById = (id: string): Trip => {
    const found = defaultTrips.find((t) => t.id === id);
    return found || defaultTrips[0];
  };

  return {
    trips: defaultTrips,
    getTripById,
  };
}
